SET SERVEROUTPUT ON

DECLARE
    CURSOR C_T_MC_SGV_OCORRENCIA_SAC IS
        SELECT 
        SAC.NR_SAC, SAC.DT_ABERTURA_SAC, SAC.HR_ABERTURA_SAC, SAC.TP_SAC, SAC.NR_INDICE_SATISFACAO, 
        CAT.CD_CATEGORIA, CAT.TP_CATEGORIA, CAT.DS_CATEGORIA,
        PRO.CD_PRODUTO, PRO.TP_EMBALAGEM, PRO.VL_UNITARIO, PRO.VL_PERC_LUCRO,
        EST.SG_ESTADO, EST.NM_ESTADO, CID.NM_CIDADE, BAI.NM_BAIRRO,
        CLI.NR_CLIENTE, CLI.NM_CLIENTE, CLI.QT_ESTRELAS
        
        FROM T_MC_CATEGORIA_PROD CAT INNER JOIN T_MC_PRODUTO PRO
        ON(CAT.CD_CATEGORIA = PRO.CD_CATEGORIA)
        INNER JOIN T_MC_SGV_SAC SAC
        ON(PRO.CD_PRODUTO = SAC.CD_PRODUTO)
        INNER JOIN T_MC_CLIENTE CLI
        ON(CLI.NR_CLIENTE = SAC.NR_CLIENTE)
        INNER JOIN T_MC_END_CLI END
        ON(CLI.NR_CLIENTE = END.NR_CLIENTE)
        INNER JOIN T_MC_LOGRADOURO LOG
        ON(LOG.CD_LOGRADOURO = END.CD_LOGRADOURO_CLI)
        INNER JOIN T_MC_BAIRRO BAI
        ON(BAI.CD_BAIRRO = LOG.CD_BAIRRO)
        INNER JOIN T_MC_CIDADE CID
        ON(CID.CD_CIDADE = BAI.CD_CIDADE)
        INNER JOIN T_MC_ESTADO EST
        ON(EST.SG_ESTADO = CID.SG_ESTADO);
      
 BEGIN
    FOR CUR_OCORRENCIA IN C_T_MC_SGV_OCORRENCIA_SAC LOOP
    DBMS_OUTPUT.PUT_LINE ('Número da ocorrência do SAC:' || CUR_OCORRENCIA.NR_SAC);
    DBMS_OUTPUT.PUT_LINE ('Data de abertura do SAC:' || CUR_OCORRENCIA.DT_ABERTURA_SAC);
    DBMS_OUTPUT.PUT_LINE ('Hora de abertura do SAC:' || CUR_OCORRENCIA.HR_ABERTURA_SAC);
    DBMS_OUTPUT.PUT_LINE ('Tipo do SAC:' || CUR_OCORRENCIA.TP_SAC);
    DBMS_OUTPUT.PUT_LINE ('Número do índice de satisfação SAC:' || CUR_OCORRENCIA.NR_INDICE_SATISFACAO);
    DBMS_OUTPUT.PUT_LINE ('Código da categoria do produto:' || CUR_OCORRENCIA.CD_CATEGORIA);
    DBMS_OUTPUT.PUT_LINE ('Tipo da categoria do produto:' || CUR_OCORRENCIA.TP_CATEGORIA);
    DBMS_OUTPUT.PUT_LINE ('Descrição da categoria do produto:' || CUR_OCORRENCIA.DS_CATEGORIA);
    DBMS_OUTPUT.PUT_LINE ('Código do produto:' || CUR_OCORRENCIA.CD_PRODUTO);
    DBMS_OUTPUT.PUT_LINE ('Nome do produto:' || CUR_OCORRENCIA.CD_PRODUTO);
    DBMS_OUTPUT.PUT_LINE ('Embalagem do produto:' || CUR_OCORRENCIA.CD_PRODUTO);
    DBMS_OUTPUT.PUT_LINE ('Valor unitario de venda do produto:' || CUR_OCORRENCIA.CD_PRODUTO);
    DBMS_OUTPUT.PUT_LINE ('Percentual do lucro unitário do produto:' || CUR_OCORRENCIA.CD_PRODUTO);
    DBMS_OUTPUT.PUT_LINE ('Sigla do Estado:' || CUR_OCORRENCIA.SG_ESTADO);
    DBMS_OUTPUT.PUT_LINE ('Nome do Estado:' || CUR_OCORRENCIA.NM_ESTADO);
    DBMS_OUTPUT.PUT_LINE ('Nome da Cidade:' || CUR_OCORRENCIA.NM_CIDADE);
    DBMS_OUTPUT.PUT_LINE ('Nome do Bairro:' || CUR_OCORRENCIA.NM_BAIRRO);
    DBMS_OUTPUT.PUT_LINE ('Número do Cliente:' || CUR_OCORRENCIA.NR_CLIENTE);
    DBMS_OUTPUT.PUT_LINE ('Nome do Cliente:' || CUR_OCORRENCIA.NM_CLIENTE);
    DBMS_OUTPUT.PUT_LINE ('Quantidade de estrelas do cliente:' || CUR_OCORRENCIA.QT_ESTRELAS);
    DBMS_OUTPUT.PUT_LINE ('');
    
    END LOOP;
 END;   
/
