CREATE OR REPLACE TRIGGER tr_t_mc_cli_fisica  
BEFORE INSERT OR UPDATE ON t_mc_cli_fisica 

FOR EACH ROW 
BEGIN 

    CASE
    WHEN INSERTING THEN
        IF  FN_VALIDA_CPF(:new.NR_CPF)='VALIDO' then dbms_output.put_line('Inserindo registro de CPF: '||:New.NR_CPF);
        ELSIF FN_VALIDA_CPF(:new.NR_CPF)= 'INVALIDO' then RAISE_APPLICATION_ERROR(-20001,'CPF INVALIDO') ;     
        ELSE RAISE_APPLICATION_ERROR(-20002,'ERRO DESCONHECIDO');
        END IF;
    WHEN UPDATING THEN
        IF  FN_VALIDA_CPF(:new.NR_CPF)='VALIDO' then dbms_output.put_line('Atualizando registro de CPF: '||:New.NR_CPF);
        ELSIF FN_VALIDA_CPF(:new.NR_CPF)= 'INVALIDO' then RAISE_APPLICATION_ERROR(-20001,'CPF INVALIDO') ;     
        ELSE RAISE_APPLICATION_ERROR(-20002,'ERRO DESCONHECIDO');
        END IF;
    END CASE;
END; 
/



INSERT ALL
INTO T_MC_CLI_FISICA (NR_CLIENTE,DT_NASCIMENTO,FL_SEXO_BIOLOGICO, DS_GENERO,NR_CPF) VALUES (11,TO_DATE('15/09/2000','DD/MM/YYYY'),'F','Feminino','24022507047')
SELECT * FROM DUAL;
COMMIT;
